/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

/**
 *
 * @author CaioVDetoni
 */

/**
 * Sistema de Pagamento de Passagem de Ônibus Linha 3.33 Campinas
 * 
 * Este sistema simula o cálculo do valor proporcional de uma passagem
 * com base no número de paradas percorridas pelo passageiro.
 * da linha 3.33, Campinas, SP.
 * O itinerário completo contém 20 paradas, e o valor total da passagem
 * é de R$ 5,70. O usuário seleciona a parada no JComboBox, e o sistema 
 * calcula o valor proporcional exibindo o resultado na tela.
 * 
 * Funcionalidades principais:
 * - Selecionar o itinerário (parada) percorrido.
 * - Calcular o valor proporcional da passagem.
 * - Exibir o resultado formatado em um JLabel.
 */

public class telaValorPassagem extends javax.swing.JFrame {

    /**
     * Creates new form telaValorPassagem
     */
    public telaValorPassagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboParadas = new javax.swing.JComboBox<>();
        botaoCalcular = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de Pagamento de Passagem de Ônibus");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Selecione o itinerário");

        comboParadas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        comboParadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - TERMINAL BARAO GERALDO", "2 - AV DR MORAES SALLES (CORREDOR EXTERNO)", "3 - ACESSO", "4 - R IRMA SERAFINA", "5 - R OSCAR ALVES COSTA", "6 - AV ANCHIETA (CORREDOR EXTERNO)", "7 - R ALBINO JOSE BARBOSA DE OLIVEIRA", "8 - AV OROSIMBO MAIA", "9 - ACESSO", "10 - AV BRASIL", "11 - RODV PROF ZEFERINO VAZ (SP-332)", "12 - AV BR DE ITAPURA", "13 - R FUNILENSE", "14 - R CAROLINA FLORENCE", "15 - R DR BUARQUE DE MACEDO", "16 - RODV PROF ZEFERINO VAZ (SP-332)", "17 - AV BR DE ITAPURA", "18 - R DOS PARECIS", "19 - R CAROLINA FLORENCE", "20 - AV PRES COSTA E SILVA" }));

        botaoCalcular.setText("Calcular Valor");
        botaoCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcularActionPerformed(evt);
            }
        });

        labelResultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelResultado.setText("Valor da Viagem");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel3.setText("Linha 3.33");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/onibus.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboParadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(botaoCalcular))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(labelResultado)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboParadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelResultado)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcularActionPerformed
        // TODO add your handling code here:
        
        // Define o valor total da passagem e o total de itinerários
double valorPassagemCompleta = 5.70; // Valor para o itinerário completo
int totalItinerarios = 20; // Total de paradas no trajeto

// Obtém o itinerário selecionado no JComboBox
String itemSelecionado = (String) comboParadas.getSelectedItem();

// Extrai o número do itinerário antes do hífen
int paradasPercorridas = Integer.parseInt(itemSelecionado.split("-")[0].trim());

// Calcula o valor proporcional com base nas paradas percorridas
double valorAPagar = (paradasPercorridas * valorPassagemCompleta) / totalItinerarios;

// Exibe o valor calculado no JLabel
labelResultado.setText("O valor a pagar é: R$ " + String.format("%.2f", valorAPagar));
    }//GEN-LAST:event_botaoCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaValorPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaValorPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaValorPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaValorPassagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaValorPassagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCalcular;
    private javax.swing.JComboBox<String> comboParadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelResultado;
    // End of variables declaration//GEN-END:variables
}
